### ISSUE TITLE
Translation of other types

### ISSUE THREAD

**Issue by debz7889** [MoienTajik/GraphQL.Tools#3]
Is it there a way to replace or translate types(scalars) from another language to C# equivalents using GraphQL.Tools?

Like:
scalars:
            DateTime: DateTime
            Long: long
            Int: int
            Boolean: bool
            Uuid: string
            Decimal: double
            Byte: int
            RowVersion: string
            Short: int

**Comment by MoienTajik** [comment]
It's possible if you have a GraphQL schema file. (schema first approach)
